### ISSUE TITLE
Horses do not properly follow player teleportation while being ridden

### ISSUE THREAD

**Issue by mb243** [MLG-Fortress/PopulationDensity#10]
Players report that when riding a horse, it does not follow when teleporting from one region post to another. Horses on leads seem to work fine. 

When I was able to get a horse to follow me, they became stuck on top of the sign at the very top of the region post. (LaunchAndDropPlayers: false)

Could this be an issue with the new entity naming in 1.11?

**Comment by mb243** [comment]
[Tue Jan 24 05:50:20 UTC 2017 INFO] This server is running CraftBukkit version git-Spigot-b32c8f8-4d3bf20 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Plugin version 5.9

**Comment by RoboMWM** [comment]
> Could this be an issue with the new entity naming in 1.11?

Very likely.
