### ISSUE TITLE
Possible Bug: Bottom Block of Post is incorrect

### ISSUE THREAD

**Issue by Spoonerj1** [MLG-Fortress/PopulationDensity#101]
![2021-06-26_01 25 23](https://user-images.githubusercontent.com/44783679/123505622-71687980-d61d-11eb-950d-11aad8d86487.png)
When I loaded this in 1.17 paper build #47 from their website, I noticed that the bottom block of the region post is not the block configured. My config is:
  PostDesign:
    TopBlock: NETHERITE_BLOCK
    MidTopBlock: NETHERITE_BLOCK
    MidBottomBlock: NETHERITE_BLOCK
    BottomBlock: GLOWSTONE
    PlatformOuterRing: SMOOTH_STONE
    PlatformInnerRing: SMOOTH_STONE
but the BottomBlock of the post is the same as the PlatformInnerRing block. I end up with no glowstone block as expected. (yes I know the glowstone would be blocked anyway, I'm just trying to see why that lowest block isn't matching config)

Edit: add screenshot

**Comment by RoboMWM** [comment]
Does this work in 1.16?

**Comment by Spoonerj1** [comment]
It appears to be the same issue in 1.16.  the config is: 
```
    TopBlock: POLISHED_BASALT
    MidTopBlock: POLISHED_BASALT
    MidBottomBlock: POLISHED_BASALT
    BottomBlock: POLISHED_BASALT
    PlatformOuterRing: SMOOTH_STONE
    PlatformInnerRing: SMOOTH_STONE
```
And this was the post:
![2021-06-27_18 47 23](https://user-images.githubusercontent.com/44783679/123564857-32027000-d778-11eb-8550-c2f507fc4367.png)

Paper(345) 1.16.4-R0.1-SNAPSHOT
PopulationDensity 5.13

**Comment by RoboMWM** [comment]
This was added in #48, can you take a look @FrankHeijden?

**Comment by FrankHeijden** [comment]
Interesting, thats a very old PR haha. From a quick glance at the code, I think its a matter of the order in which the blocks are placed.

https://github.com/MLG-Fortress/PopulationDensity/blob/209633cba1d1dd9c86c4bf1b227ee8d3418e3770/src/me/ryanhamshire/PopulationDensity/DataStore.java#L588-L610

First, the post is build, after which the bottom block is overwritten by the placement of the outer (and inner) platform. Changing the order of these two operations would fix the problem :)

**Comment by Spoonerj1** [comment]
Thanks!
