### ISSUE TITLE
Config option to disable dropping players on first join

### ISSUE THREAD

**Issue by zedwick** [MLG-Fortress/PopulationDensity#11]
I would suggest having this as a separate config option to the new PopulationDensity.LaunchAndDropPlayers config. So we can choose to keep it for new players and disable for other teleportation, or (as I would like) to disable it for new players and keep it enabled for other teleportation.

**Comment by RoboMWM** [comment]
Feel free to PR that.

**Comment by zedwick** [comment]
PR added. I've not contributed to another project before, so feel free to let me know if there's any issues with it.
