### ISSUE TITLE
Disable animal teleportation

### ISSUE THREAD

**Issue by FrankHeijden** [MLG-Fortress/PopulationDensity#14]
Heya!
My players are experiencing a problem with populationdensity. Animals spawn on regioposts, and even get teleported to the regiopost despite they are already in a farm of a player. How do I toggle this off? In my config file i have set respawn animals false, so that's not an option anymore what it could be.
-Frank

**Comment by RoboMWM** [comment]
Your players are too close to animals when they teleport.

**Comment by FrankHeijden** [comment]
How do I disable this if I may ask?

**Comment by RoboMWM** [comment]
When someone makes a PR for it.

**Comment by FrankHeijden** [comment]
And is there also another way to disable this?

**Comment by RoboMWM** [comment]
I don't know, I actually disabled post teleportation on my server, so even if I were to implement such a feature I would not be able to test it as easily (which is my primary reason why I'm not in a hurry to implement this - but I may take a look at it during my break or something). Big_Scary's recommendation was to make sure players are away from animals before teleporting.

**Comment by FrankHeijden** [comment]
Some servers aren't experiencing this problem, how did they do it? or have you absolutely no idea? People are trying to 'steal' other animals to their region at my server :(

**Comment by RoboMWM** [comment]
> Big_Scary's recommendation was to make sure players are away from animals before teleporting.

**Comment by RoboMWM** [comment]
You may also want to only allow teleporting when near a post.

**Comment by FrankHeijden** [comment]
Could you please fix this? People are stealing each others animals with this bugg. And I cant make sure players are away from animals before teleporting because they found out they can steal each others animals...

**Comment by zedwick** [comment]
I will probably have a go this at some point, in the mean time you may try using another plugin (skript?) to deny using PD's commands if there are animals nearby.

**Comment by RoboMWM** [comment]
In addition, you could do what I suggested above - only allowing teleportation near region posts.

**Comment by FrankHeijden** [comment]
@zedwick Ok, ty
When will it be released for public? 😃

**Comment by zedwick** [comment]
@FrankHeijden Sorry, I've not yet had the time available to look at it. It's just something I will probably look at when I'm looking to take a break from other projects. No guarantees this will be soon.

**Comment by FrankHeijden** [comment]
haha ok, no problem :)
