### ISSUE TITLE
"An internal error occurred while attempting to perform this command"

### ISSUE THREAD

**Issue by spacepuppy** [MLG-Fortress/PopulationDensity#18]
Hi,

I've just installed this plugin and this is the response I receive when I type in /whichregion
I understand this is likely because I don't have any NEW players on my server.

The plugin displays green when I list my servers plugins and I've been unable to find an answer anywhere on the internet to explain this issue.

Thanks

**Comment by RoboMWM** [comment]
Well, pasting the error from the console logs might help.

**Comment by spacepuppy** [comment]
sorry, forgot to do that!
https://pastebin.com/RACwgnbn

**Comment by RoboMWM** [comment]
Can you ensure you're using version 5.10?

Either that, or maven/something is cutting off the "0" when it gets the plugin version...

**Comment by spacepuppy** [comment]
Yes, I'm using 5.10
I've just double checked and it's still the same.

How can I change it so it doesn't cut off the "0" ?

**Comment by RoboMWM** [comment]
So it seems that your corresponding message in messages.yml is null or not present: https://github.com/TechFortress/PopulationDensity/blob/6c6711b2b856fe467bd1cff470fb7684703517d0/src/me/ryanhamshire/PopulationDensity/PopulationDensity.java#L589

This message is printed whenever you execute the command outside of the "managedWorld" (where the posts spawn) as specified in the config. Mind pasting your messages.yml?

**Comment by RoboMWM** [comment]
Closed due to inactivity
