### ISSUE TITLE
Cannot TP whilst riding a horse

### ISSUE THREAD

**Issue by zedwick** [MLG-Fortress/PopulationDensity#20]
Cannot use /visit or /homeregion whilst riding a horse. Doing so give no chat or log message, just silently fails and does not TP the player.

However, you can if you have the permission node "populationdensity.teleportanywhere".

**Comment by RoboMWM** [comment]
I know you can't teleport if something is mounted to your head (i.e. riding you), not sure if vice versa is also the case... however, it does seem to work if you have said permission. So that's interesting. Are you near a region post when attempting to do so? What's the config?

**Comment by zedwick** [comment]
Players must be near a region post in order to teleport on my server, and they are by a region post when teleporting. I had taken a cursory glance over the code, and I believe it may be due to the protection against spamming /visit when in the air post-teleport, as it simply checks if the player is onGround. I assume when riding a horse, they are in fact not onGround.

**Comment by iNko97** [comment]
```
//disallow spamming commands to hover in the air

		if(!(player.isOnGround()||(player.getVehicle()!=null&&player.getVehicle().isOnGround()))) return new CanTeleportResult(false);
```

On my server I fixed it this way
