### ISSUE TITLE
Region Posts are not Generated

### ISSUE THREAD

**Issue by Goldentoenail** [MLG-Fortress/PopulationDensity#23]
Spigot 1.12 PopulationDensity 5.10
Everything appears to be OK with no errors in the console log.
On a newly created server using the default configurations.

When I log in I am teleported and dropped into the Redstone region and there is no region post.
Confirmed by teleporting to /spawn and then /visit redstone
There is no region post.

**Comment by Goldentoenail** [comment]
Ah, it is OK it was just in the first region.

It would be good if this was mentioned somewhere.

**Comment by RoboMWM** [comment]
Latest version is 5.11 (which appears as 5.1 I've been told). Try `addregionpost` to regenerate the post.

**Comment by Goldentoenail** [comment]
I'm not certain how this happens.

It would appear that the first region created at 0,0 does not generate a region post automatically.
But that is fine for me when I call the first region 'spawn' anyway (instead of 'redstone').


________________________________

**Comment by RoboMWM** [comment]
That's weird - region posts generate automatically for me. All I could imagine is that the chunk is already loaded before PopulationDensity is able to be enabled (and thus no chunkloadevent is fired for that chunk).
