### ISSUE TITLE
Slime Blocks Replacing Region Post :O!

### ISSUE THREAD

**Issue by ghost** [MLG-Fortress/PopulationDensity#27]
Copied from SpigotMC to here for Robo's tracking.

> I have a couple of problems here. Someone on my server used pistons in such a way that they replaced the region post with slime blocks!
> https://cloudup.com/i7tTzIZHeKm

Thanks

**Comment by RoboMWM** [comment]
Basically, try to find out how this happened. Then we can start working towards a solution.

**Comment by ghost** [comment]
Somehow... pistons were used to displace the normal blocks of the region post. If I learn more I'll keep you updated.
