### ISSUE TITLE
More PostDesign customization options, to be able to place beacons.

### ISSUE THREAD

**Issue by Fusionette** [MLG-Fortress/PopulationDensity#29]
I would like all my Region Posts to generate with beacons so they can be seen from afar. Unfortunately, the closest I can get is this:

  PostDesign:
    TopBlock: '95:4'
    PostBlocks: '138:0'
    PlatformOuterRing: '89:0'
    PlatformInnerRing: '42:0'

Which almost works, but the "PlatformInnerRing" does not include the block directly under the post, so the beacon doesn't activate. What I'd want is "PlatformInnerRing" to include the 9 blocks under the post; that alone solves the issue, though having two Beacons of each other looks kind of weird.

Ideally, the main post blocks would be defined as "TopBlock", "MiddleBlock" and "BottomBlock" for further customization. so I can have an PlatformInnerRing (9 blocks) of Iron, a Beacon BottomBlock, then glass in TopBlock and MiddleBlock in order to let the beacon through.

This does leave the sign at the top half-covered by the beacon beam, which might be an issue. I propose solving this by having an option which moves that sign from the top, to the free side on the top block; the sign with the World Name faces north, the sign with the Region Name would face south.

**Comment by RoboMWM** [comment]
Yea, we're going to have to fix this up for 1.13 as well. Right now all this post generation stuff is hardcoded in.

**Comment by smellyonionman** [comment]
Maybe an option to specify a BO3 file could make life easier for a lot of people?

**Comment by RoboMWM** [comment]
Nope, iirc that's a TerrainControl-specific file, and thus will only work with TerrainControl (unless I hook into that). Same as if it were to use schematics.

However, I'm sure there's a desire to use either; this currently uses the bukkit API to place blocks directly in the world, which keeps it simple and as performant as the bukkit implementation is, as well as being relatively future-proof (obviously not so with 1.13's major changes to block id's). So maybe an addon? Then that'll solve the issue of having to add a ton of config nodes.

**Comment by smellyonionman** [comment]
You could implement a chest GUI where the pillar is built out of blocks.

It would be just one face and the changes would be (most easily) applied to all four faces.  It does limit the pillar to a 9x6y9z area, but that still allows for a fully powered beacon with room for two pieces of stained glass, and the required slew of config nodes are instantly more accessible.

**Comment by spooner01** [comment]
I too would love to see this in the next update. I just posted in the forums on spigot but then realized my error in not checking here first.
