### ISSUE TITLE
/spawn is replaced by /homeregion

### ISSUE THREAD

**Issue by nukemonk** [MLG-Fortress/PopulationDensity#33]
Hi,

After installing this plugin /spawn teleports you to your homeregion post instead of the world spawn. Is this normal? Is there any way to make /spawn teleport you to the world spawn?

**Comment by RoboMWM** [comment]
Can't recall if `/spawn` was supposed to take you to the `/cityregion` (which is usually around spawn) - you might need to configure said cityregion.

If you want to modify which command is handled by which plugin, use bukkit's included [commands.yml](https://bukkit.gamepedia.com/Commands.yml)

**Comment by nukemonk** [comment]
Thank you for your swift reply! I will try to edit the commands.yml soon. For now I have a temporary solution by installing a separate spawn plugin.

But in stead of cityregion it teleports you to homeregion. If I use /movein on a different region /spawn will teleport me to that said region.

**Comment by RoboMWM** [comment]
The alias is for /cityregion, though you do have to set that up before it's used, otherwise it just defaults to /homeregion.

**Comment by nukemonk** [comment]
I want to thank you for sharing your knowledge with me. I set an alias for essentialsspawn:spawn and now it works just the way I want it. Thanks! :+1:
