### ISSUE TITLE
WorldGuard flag conflicts

### ISSUE THREAD

**Issue by smellyonionman** [MLG-Fortress/PopulationDensity#34]
I've been trying to get to the bottom of an issue with my spawn region, wherein WorldGuard was not suppressing the growth of my grass.  I've finally traced the issue to PopulationDensity's option to regrow the grass in a given region.

Since you're updating for 1.13 (thank you,) I figured it might be a good opportunity to check for WorldGuard flags or code in a way that is influenced by them.  Disabling is an okay solution, I guess, but 'just so you know.'

**Comment by RoboMWM** [comment]
This doesn't hook into WorldGuard, and I'd like really like to avoid doing that - at least inside this plugin. An addon could take care of it, perhaps.

Anyways, grass regrowth _should_ only occur when a new player joins, and in the current new player region.

**Comment by RoboMWM** [comment]
Best way is to either disable regrow grass or move the new player post region, since I assume it's only in a specific area.
