### ISSUE TITLE
using /listregions crashes players instantly.

### ISSUE THREAD

**Issue by Mrs-Feathers** [MLG-Fortress/PopulationDensity#35]
<img width="707" alt="screen shot 2018-04-10 at 19 47 40" src="https://user-images.githubusercontent.com/1746550/38589275-122ee862-3cf8-11e8-9e7b-d8c8d03bd6ad.png">

this is the screenshot of what happens if you type /listregions

i am using version 5.10
and minecraft bukkit server 1.12.2

**Comment by RoboMWM** [comment]
I'm going to guess you probably have a region name with some invalid characters. Look in the plugin folder.

**Comment by Mrs-Feathers** [comment]
thanks!! i deleted the database and restarted the server, let it rename everything and it works perfectly!
