### ISSUE TITLE
Adding command: trust player in all claims

### ISSUE THREAD

**Issue by spooner01** [MLG-Fortress/PopulationDensity#36]
I've had a few players on my server ask for a command to trust a player across all of your claims, not just the one you're in. 
Some players like to build a small base with many remote areas, using claims to protect them, but going around to /trust a player in every claim is a hassle. Having a /trustallclaims {player} command would be awesome to allow friends to access claims

**Comment by RoboMWM** [comment]
This is the issue tracker for PopulationDensity, not GriefPrevention. And you just use /trust outside of a claim to trust them to all claims.
