### ISSUE TITLE
Creative mode can't fly.

### ISSUE THREAD

**Issue by Mrs-Feathers** [MLG-Fortress/PopulationDensity#37]
Hello! i have a server with population density [latest version off the dev.bukkit.com site.. and Essentials v2.0.1 and plugman. the server version is 1.12.2 of spigot.

and the issue is that when i go to creative mode or anyone does, they can't fly. only for the first time trying to fly. and it lasts an indeterminate amount of time and people can fly again once population dencity is disabled. when reenabled, people who weren't able to fly can fly. however, if this is the first time a player has been put into creative, after its been reenabled, they cannot fly. the "list" of players not able to fly seems to be reset when the world is reset.. but apparently has nothing to do with the player data files for inventory and stuff.. because i've been deleting my own file over and over trying to reproduce this bug.

i have zero idea whats going on.. and its not like theres a "stop players from flying: true" in the config.. so i'm reporting this as a bug. and i assume its this plugin because when i disable it, we all can fly.. and the only other plugin is essentials. if i disable essentials, nothing happens. we're still grounded.

**Comment by RoboMWM** [comment]
Via a github search it seems there's zero places where `player#setAllowFlight` is called, so I don't see how PopulationDensity can be responsible for this. I do know it has something to prevent gliding, but this only applies to players who teleport to a post and `launchAndDropPlayers` is enabled.

**Comment by Mrs-Feathers** [comment]
thats so weird… maybe i can disable anything having to do with flying on essentials? all i know is when i disable /your/ plugin, everything works.

**Comment by RoboMWM** [comment]
I haven't had any issues with creative mode when I used PopulationDensity, but there have been reports like #13 

https://github.com/BigScary/PopulationDensity/blob/0bd9c4cfd35bea73538604dc91a6cd099c02493a/src/me/ryanhamshire/PopulationDensity/PlayerEventHandler.java#L394

So there's this. But players who are set as fall damage immune should only be those that were teleported recently. However, PopulationDensity does add the player to both an internal map AND metadata (presumably I assume in the case a player logs out while falling), so your disabling of the plugin is probably preventing PopulationDensity from being able to clear this metadata entry.

**Comment by RoboMWM** [comment]
I guess to support administrators who do not-so-very-good-things (i.e. adding support for on-demand disabling and enabling), I could have it store a UUID in the map and just check that. Though this does provide the possibility that someone does in fact need this fall damage immunity but because the plugin was disabled/enabled, they no longer have it... hmmm...

**Comment by Mrs-Feathers** [comment]
well i mean, essentials does have /god mode. god mode is survival mode with no combat damage and no fall damage, no environmental damage, etc. its possible that god mode on is messing with it, even thought i’m not even in survival. like even in creative, i’ve gotten the “nocheatplus” giving false errors for god mode’s immunity. the only people who are flying are admin. and its very possible they’re doing /god mode and then just not telling me… i’ll look into it. i know its a wild assumption. but its the only one that makes sense from the post you just linked me. and its possible that resetting the server resets essential’s settings which reset the god mode settings...

**Comment by ghost** [comment]
Same issue should get fixed by pull #40, as it removes that :D

**Comment by RoboMWM** [comment]
As mentioned by Developaws, https://github.com/TechFortress/PopulationDensity/commit/d72fda41263f20810acf638bc8698dcfc24e54d9 closes this by checking for immunity on every single movement instead of only when fall damage is taken.
