### ISSUE TITLE
Unlimited hoppers below MinimumRegionPostY

### ISSUE THREAD

**Issue by zedwick** [MLG-Fortress/PopulationDensity#43]
All players can place unlimited hoppers below MinimumRegionPostY, but are restricted by the "Maximum Hoppers Per Chunk" above that.

**Comment by RoboMWM** [comment]
~~Wait a minute, I don't think this plugin does anything with hoppers.~~ Huh. I guess Big_Scary might've added hopper restrictions to _both_ GP (creative claims) and here.


Probably as simple as changing a boolean when checking within a region.

**Comment by ghost** [comment]
Resolved.

**Comment by RoboMWM** [comment]
Oops, referenced wrong issue when fixing up the commit message :c
