### ISSUE TITLE
Use Travis?

### ISSUE THREAD

**Issue by NatoBoram** [MLG-Fortress/PopulationDensity#49]
Would adding Travis-CI help the project?

It automatically builds the project and tells GitHub if it could build it successfully. [Spigot used it!](https://travis-ci.org/SpigotMC/Spigot)

Alternatively, [GitLab-CI](https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/github_integration.html) can also be added to build the project.

**Comment by RoboMWM** [comment]
AppVeyor seems to be working fine?

**Comment by NatoBoram** [comment]
Yes, it does! In my personal GitHub projects, I don't like to rely on a single CI, I like to hug as many free services as possible. I like to collect badges, hehe.

One other project I found to be interesting is [CodeClimate](https://codeclimate.com/oss/dashboard). It helps to find code smells in my projects (and god do my code smells).
