### ISSUE TITLE
Teleporting to region posts disables flying

### ISSUE THREAD

**Issue by RoboMWM** [MLG-Fortress/PopulationDensity#5]
Yes, there's still code in here to disable flying (probably to prevent Elytra use). I personally don't use the post teleportation feature however, so it might be a while before I can visit this issue and figure out how to best deal with it.

**Comment by RoboMWM** [comment]
FYI to anyone following this issue - I'm not looking into this issue anymore since the entire launching/dropping feature can be disabled, but if you have more details to add/want to PR a fix, feel free to do so.

**Comment by zedwick** [comment]
I'm not able to reproduce from the description in #13 on my server.

**Comment by RoboMWM** [comment]
Since we have an actual user report with some info, details will be present on #37
