### ISSUE TITLE
Add an option to show a custom help link or none at all.

### ISSUE THREAD

**Issue by NanoAi** [MLG-Fortress/PopulationDensity#50]
Please add the option to show a custom help message or not show a help message at all.
![image](https://user-images.githubusercontent.com/3096584/43340980-20416caa-91ac-11e8-8793-caae3e3cf2ed.png)

The reason I'd like to be able to change this is because we've edited the CFG to not allow teleportation and the tutorial linked confuses players.

**Comment by RoboMWM** [comment]
You can, messages.yml.
