### ISSUE TITLE
1.13 Compatability

### ISSUE THREAD

**Issue by ArZorMC** [MLG-Fortress/PopulationDensity#54]
I recently found this plugin and was hoping to use it on my 1.13 server once we update.
Trying it out first on a dev. server running paper-spigot version git-Paper-134 i got this error on startup:
https://pastebin.com/85dzS9aR

**Comment by ArZorMC** [comment]
After deleting all the old worlds and having new 1.13 world generates the first error went away and instead i got this one on startup:
https://pastebin.com/ud4AYLLy

**Comment by RoboMWM** [comment]
Forgot to release a beta build of a 1.13-compiled build since I had limited internet for the past two weeks, so I'll do that now.

**Comment by RoboMWM** [comment]
As soon as it's approved, https://dev.bukkit.org/projects/population-density/files/2604116
