### ISSUE TITLE
Spam in chat when using /visit

### ISSUE THREAD

**Issue by Spoonerj1** [MLG-Fortress/PopulationDensity#61]
Players on my server are smacked with a ton of spam when using /visit {region}. 
Happens anytime using /visit. You do not have to tab complete to get the error, it just spams the chat as you type.

![unknown](https://user-images.githubusercontent.com/44783679/48017637-fd83a680-e0eb-11e8-8f8e-2b0fe4811152.png)

**Comment by RoboMWM** [comment]
Did tab completion change? Thinking it may have to do with the names of your region(s).

**Comment by Spoonerj1** [comment]
We are using standard names from the config except for a few regions. Its the same no matter what name we use

**Comment by RoboMWM** [comment]
It iterates through all names, so it matters what names are in use.

**Comment by Spoonerj1** [comment]
- Redstone
  - Dew
  - Utah
  - Wisconsin
  - Minnesota
  - Oregon
  - California
  - Colorado
  - NewYork
  - Florida
  - Carolina
  - Honolulu
  - Creeper
  - Sword
  - Wintersebb
  - Fjord
  - Vista
  - Breeze
  - Tide
  - Glenwood
  - Journey
  - Cragstone
  - Pickaxe
  - Axe
  - Hammer
  - Anvil
  - Mist
  - Sunrise
  - Sunset
  - Copper
  - Coal
  - Shovel
  - Minecart
  - Railway
  - Dig
  - Chasm
  - Basalt
  - Agate
  - Boat
  - Grass
  - Gust
  - Ruby
  - Emerald
  - Stone
  - Peak
  - Ore
  - Boulder
  - Hilltop
  - Horizon
  - Fog
  - Cloud
  - Canopy
  - Gravel
  - Torch
  - Obsidian
  - Treetop
  - Storm
  - Gold
  - Canopy
  - Leaf
  - Summit
  - Glade
  - Trail
  - Seed
  - Diamond
  - Armor
  - Sand
  - Flint
  - Field
  - Steel
  - Helm
  - Gorge
  - Campfire
  - Workshop
  - Rubble
  - Iron
  - Chisel
  - Lunar
  - Shrub
  - Zombie
  - stem
  - Vale
  - Pumpkin
  - Lantern
  - Copper
  - Beam
  - Soil
  - Dust

All the names in use by the server. 
We have regions named ShoppingDistrict, SpoonCity, TheHive, Iceberg, and Olympus that obviously aren't in the list. Are spaces in Region Names allowed or no? I assumed no

**Comment by RoboMWM** [comment]
Need server log of exception btw.

**Comment by Spoonerj1** [comment]
https://pastebin.com/Pcy9KyZj

This photo is after using /visit Mall. The teleportation works as expected.
![2018-11-06_12 09 06](https://user-images.githubusercontent.com/44783679/48081170-a560a900-e1ac-11e8-9473-8157638e6f2f.png)

**Comment by RoboMWM** [comment]
There's no tabcompletion package in PopulationDensity nor a TabCompletionUtil, so idk what the heck you're running... obviously not this version of PopulationDensity

**Comment by RoboMWM** [comment]
Yea, you're running version 5.8.9, which I guess means you're running some fork.

**Comment by RoboMWM** [comment]
version 5.8.9 of populationdensity, so yea, you're running something other version of PopulationDensity. Definitely not from here.

**Comment by RoboMWM** [comment]
Yea, you're running @Dogeveloper's fork instead of this one.

**Comment by RoboMWM** [comment]
You can download the official version (this repo) here http://dev.bukkit.org/bukkit-plugins/population-density/

**Comment by gnubufferoverflows** [comment]
@Spoonerj1 If you want to report issues with my fork, please do it here: https://github.com/Dogeveloper/PopulationDensity/issues

In your case I'm going to need a more comprehensive server log to figure out what is going on. The whole thing isn't necessarily required, it's just that's there is a lot of things that could be going wrong, some of them not necessarily involving a bug with the plugin.
