### ISSUE TITLE
Essentials Warps Signs on Region Posts

### ISSUE THREAD

**Issue by ichbinashh** [MLG-Fortress/PopulationDensity#65]
I was wondering if there was a way to get the EssentialsX warp signs to load automatically on to region posts, as I want users to have to travel to the post in order to be able to warp to a specific place, rather than having them use it as a bypass to travelling.

In the config, I added -
    North:
    - [Warp]
    - AuctionHouse
    - Everyone
    - ''

but it did not seem to like the [], therefore removed the entire top line. 

Is there a way to input [] without it conflicting with the code?

EDIT: I changed to '[Warp]' and instead of deleting the line, it just did not enable the warp. Any ideas?

Thank you!

**Comment by RoboMWM** [comment]
Idk how EssentialsX detects a warp sign, so you'll need to figure out their format.

**Comment by ichbinashh** [comment]
Using that exact format in game creates the sign - 

[Warp]
WarpName
GroupName
Blank

**Comment by RoboMWM** [comment]
No, it might be doing something on SignChangeEvent that adjusts it to the format they're expecting on click.

**Comment by ichbinashh** [comment]
Oh I see, I'll head over to the Essentials Discord and see if they can help at all
