### ISSUE TITLE
/vr playerName on invisible players

### ISSUE THREAD

**Issue by Muspah** [MLG-Fortress/PopulationDensity#66]
Hi all,

Based on the outcome of running /vr vanishedPlayerName, it's possible to detect if someone is vanished or not. When the given player is vanished, the commandsender gets teleported to the targetplayer's homeregion or receives a message that the targetplayer lives in the wilderness. When the targetplayer is really offline, the player receives a message that there is no player or region with the given name. It might seem a bit farfetched, but players are actually using this at the moment to find moderators in vanish.

It looks like an easy fix by checking if CommandSender#canSee(targetPlayer) around [here](https://github.com/TechFortress/PopulationDensity/blob/master/src/me/ryanhamshire/PopulationDensity/PopulationDensity.java#L646), but I'd like to check if that's possible without breaking other usecases not known to me before submitting a PR.

Thanks,
Simon

**Comment by RoboMWM** [comment]
Go ahead and PR, if there are issues in the PR we'll let you know but usually adding that check isn't an issue.
