### ISSUE TITLE
1.14.1

### ISSUE THREAD

**Issue by ichbinashh** [MLG-Fortress/PopulationDensity#68]
Hey, I was just wondering if you were working on, or planning on working on a version for 1.14.1?

Thank you

**Comment by RoboMWM** [comment]
Is the current version broken on 1.14?

**Comment by Apecengo** [comment]
It’s working fine for me on 1.14. However, there are some blocks that need
to be added to the region scan list and some new mobs to the entity
thinning one also.

I was thinking on creating a PR one of these days.

**Comment by ichbinashh** [comment]
It was throwing up a tonne of errors for me, but I didn't think to record
any of them because my console was just a big slew of them from different
plugins. I decided that it was not quite time for 1.14 and reverted
everything back for the time being.

**Comment by RoboMWM** [comment]
Ok, next time provide stacktrace please.

**Comment by ichbinashh** [comment]
I have found the time to try some more tests, and I've gathered the two errors that are being thrown into my console; https://pastebin.com/raw/DBtCDqpA

**Comment by RoboMWM** [comment]
You should probably update the original post and title to more appropriately match the issues. Also preferred to make one issue per problem.

**Comment by RoboMWM** [comment]
Reason why those two errors (the first being a warning not an error) should be in separate issues because one is indeed a 1.14-related bug (API for canceling chunk unload event was removed for some reason) but nothing game-breaking or critical other than a bit of logspam, while the other is due to 1.14's chunk loading being ultra slow ATM.

**Comment by ichbinashh** [comment]
Would you still like me to make two new posts to cover each of these?

**Comment by RoboMWM** [comment]
Yes please, thank you.

Will make it a lot easier to follow the discussion for each.

**Comment by ichbinashh** [comment]
Will do, thank you
