### ISSUE TITLE
Latest crash report

### ISSUE THREAD

**Issue by Spoonerj1** [MLG-Fortress/PopulationDensity#75]
My latest crash report shows PopDens as the culprit, wanted to post it here for your use.
[2019-07-01-5.log.gz](https://github.com/TechFortress/PopulationDensity/files/3347870/2019-07-01-5.log.gz)

**Comment by RoboMWM** [comment]
Please use something like gist next time so I can easily view the log.

**Comment by RoboMWM** [comment]
Duplicate of #69 

It's not responsible for the failed saves tho.

And it's not a crash, but a hang.
