### ISSUE TITLE
Feature request  |  remove region command

### ISSUE THREAD

**Issue by Spoonerj1** [MLG-Fortress/PopulationDensity#79]
Maybe I've missed it, but it would be great to see a /removeregion command to... well... remove regions as needed ha ha

**Comment by RoboMWM** [comment]
Use case?

**Comment by Spoonerj1** [comment]
On my server there is a region that is outside the world border, named, but cant be traveled to. I would like to remove it.

**Comment by RoboMWM** [comment]
PopulationDensity works from 0,0 in a spiral, so the next region will only be further out...? Or was this post renamed from some time ago before the worldborder was shrunk/established?

**Comment by Spoonerj1** [comment]
It exists from before the world border was shrunk. And a region is renamed automatically when a certain number of blocks are placed. So if a user waaaaay out in the wild is building a lot, then the region is named. But if that user leaves (and in my case the grief prevention claim is deleted after 30 days) then the region ends up in a "wild" state again and still has a name, but there is nothing there. 

Another case would be an admin naming a region, and then deciding to use a different region. 

Another case would be building near a region border, and renaming the region for travelers (maybe not realizing how far away the post is) and accidentally naming the wrong region. 

In any case though, it would seem that /removeregion goes right along with /addregion, like two sides of one coin.

**Comment by RoboMWM** [comment]
> In any case though, it would seem that /removeregion goes right along with /addregion, like two sides of one coin.

Not quite. /addregion does several things - it closes the currently-open region (region accepting new players), searches for a new spot with ample resources, then opens that region as the new player spawn point.

What would deleting a region do? Should users who have that region as their home still be able to use it? What if it's the currently-open region? Do we perform the same steps as addregion? Should it be available again as a candidate for being the open region?

**Comment by RoboMWM** [comment]
Idk what you have automatically naming regions, I'm not aware of any automatic feature that does that.

**Comment by RoboMWM** [comment]
In other words, I'm trying to find what `/addregion` wouldn't provide as well as understanding what your situation is since what you described is not something that's done commonly nor am familiar with.

**Comment by Spoonerj1** [comment]
the plugin names a region after a certain number of blocks are placed by players. 

Addregion doesn't help when you are trying to delete a region from the list altogether.

**Comment by RoboMWM** [comment]
You mean it opens a new region elsewhere, right?

**Comment by Spoonerj1** [comment]
No, addRegion opens a new region. 

removeRegion would delete it from the list of open/named regions entirely, resetting that region post to an unopened "wilderness" region

**Comment by RoboMWM** [comment]
Afaik, the plugin only opens a new region if the current one lacks resources or has too many "player-placed" blocks. I don't believe the plugin automatically decides to name regions that are populated - it only names them when it's scanning to open a new region.

Output of `/version PopulationDensity` just to make sure you're using this one?

**Comment by Spoonerj1** [comment]
Thats what Im referring to? I literally said "after a certain number of blocks are placed by players.".

What I'm trying to request is to delete a region or even just remove the name of the region wo it goes back to being wilderness.

16.11 22:20:01 [Server] INFO PopulationDensity version 5.12

**Comment by RoboMWM** [comment]
> And a region is renamed automatically when a certain number of blocks are placed. **So if a user waaaaay out in the wild is building a lot,** then the region is named. But if that user leaves ... then the region ends up in a "wild" state again and still has a name, but there is nothing there.

(emphasis mine)

It sounds like you're stating if players inhabit a wilderness region, then the region becomes named (thus no longer being a wilderness region).

> Thats what Im referring to?

If you're saying it's being too aggressive about closing the current region, then you just need to tweak the resource minimum setting.

**Comment by Spoonerj1** [comment]
All I'm saying is that there is no command to delete named regions, and it would be nice to have one. My case is surely not the only one, and the details of why it needs to be removed are actually irrelevant.

**Comment by RoboMWM** [comment]
> My case is surely not the only one, and the details of why it needs to be removed are actually irrelevant.

I'm not asking why it needs to be removed, but instead why the features already available aren't sufficient. If they are not sufficient, then I need to understand the what in order to implement the how for a feature.

I don't see how /addregion doesn't fulfill the ability to close an open region. The only "what" I see here that /addregion doesn't do is prevent teleportation to existing, non-wilderness posts

**Comment by Spoonerj1** [comment]
I've already described the scenario though... I have a region that is named and can be visited. But its outside the world border and causes players to "suffocate" when they get there. 
I want to remove the name so that it cant be seen in /visit commands. I dont need to open a new region, I have an open region already. 
What is needed is a way to delete the region from the /regions and /visit commands.

**Comment by RoboMWM** [comment]
> I dont need to open a new region, I have an open region already.

Isn't this open region outside of the world border too? New regions are opened further and further away from world center. This is what confuses me - how is it possible to have a non-open region past the world border while having an open one within the border?

**Comment by RoboMWM** [comment]
> Every feature story should include an “As a / I want to / Because…” block, which illustrates the motivation behind a story. Compelling the product team to specify the motivation behind a story **help illuminate what exactly the requirement is, as well as providing guidance to the developers.**

https://content.pivotal.io/blog/how-to-write-well-formed-user-stories

**Comment by RoboMWM** [comment]
> So if a user waaaaay out in the wild is building a lot, then the region is named.

This can't be true. This isn't how Population Density works. I honestly cannot understand what issue I'd be resolving.

**Comment by RoboMWM** [comment]
> it would seem that /removeregion goes right along with /addregion, like two sides of one coin.

As I mentioned in some other comment, `/addregion` doesn't just arbitrarily add a region:

1. Closes currently open region
1. Scans next region for resources (next region determined via outward spiral pattern that originates from chunk coordinate 0, 0)
    1. If insufficient, close this region and repeat step 2.
1. Open the region

What should `/removeregion` do? The steps above aren't reversible. Maybe if you can explain the steps this command would perform would help me better understand what you're asking for.

**Comment by RoboMWM** [comment]
If your idea is to merely remove the region from the list, then you can try removing the region from the data folder. No idea what the effect of that will be.

**Comment by Spoonerj1** [comment]
>Isn't this open region outside of the world border too? New regions are opened further and further away from world center. This is what confuses me - how is it possible to have a non-open region past the world border while having an open one within the border?

I have not filled the world border with named regions. I have a unique region that was inside the border, and is no longer inside the border. That region was inhabited by players who used the available resources and built until the region was automatically named. Now those players live inside the new border and that region is a death trap because `/visit dakota` takes the player beyond the border and causes them to suffocate. 

> If your idea is to merely remove the region from the list, then you can try removing the region from the data folder. No idea what the effect of that will be.

I cant simply remove the region from the data folder because the data in that folder is not named, it is given a numerical id(such as "-102 1"), and is indistinguishable from the other regions. 

> What should `/removeregion` do? The steps above aren't reversible. Maybe if you can explain the steps this command would perform would help me better understand what you're asking for.

it should remove the region from the data folder. As I have already described above.
1. User issues `/removeregion DeathValley`
2. plugin deletes corresponding region file from RegionData folder   
3. no other region is affected/opened/closed/moved into/named/renamed.

for the sake of the issue: even if an admin named the region and now is claiming that they didnt name anything, there is still an open, named region that needs to be deleted from the list of regions and that is what the command is for. I dont know how to explain this issue in a way that you will understand that `/addregion` is **not** what should be used in this case and is in fact the **opposite** of what I am requesting as a feature.

**Comment by RoboMWM** [comment]
> That region was inhabited by players who used the available resources and built until the region was automatically named.

PopulationDensity does not seek out populated regions to name them. This is why I'm confused that this issue occurred.

**Comment by RoboMWM** [comment]
> That region was inhabited by players who used the available resources and built until the region was automatically named.

PopulationDensity does not seek out populated regions to name them. This is why I'm confused that this issue occurred.

> 3.no other region is affected/opened/closed/moved into/named/renamed.

What if this were done on the open region? What about players who have the post set as their home? I'm not sure of all the consequences of deleting a region from the datastore - and as such I'm not sure what behavior would or would not be acceptable for you.

Re: files, name should be in the file and I think it corresponds to region coordinates - regions are 200x200, therefore posts are 400 blocks from each other.

**Comment by RoboMWM** [comment]
Btw I'm aware that /addregion doesn't resolve your issue, I'm trying to explain that it can't be the "opposite" of a /removeregion and also trying to understand how this issue arose in the first place since the plugin simply does not name populated regions - only regions it opens, which _only_ happens when the _currently open region_ is determined to lack resources, and it seeks out new regions in a spiral pattern from spawn. So the only explanation is that someone has done a /renameregion on that region and that's what you want to undo. Is this guess correct?

**Comment by RoboMWM** [comment]
Hmm, must've misclicked a button, didn't intend to close this.

**Comment by Spoonerj1** [comment]
I think the best way to explain this issue would be to show you. 

You can join the server at Play.spooncraftmc.com, the region is named TheOutside, it will kill you upon arrival.

> What if this were done on the open region? What about players who have the post set as their home?

If I was making this, it would not affect the open region, it would have to exclude that. Any other region could be deleted and all it would do is remove the name of the region so that you cant use `/visit` unless someone living there invited you. 

The region files in the region data folder are not named, nor can they be edited unless there is some way to do so using an nbt editor. They dont even have a file extension. 

> So the only explanation is that someone has done a /renameregion on that region and that's what you want to undo. Is this guess correct? 

Yes, even just removing the name would be fine, I believe that would solve the issue.

**Comment by RoboMWM** [comment]
Just open in notepad++ or via any other text editor. They're just text files without an extension.

I'm still curious how this happened though.

**Comment by RoboMWM** [comment]
Still curious how 

> And a region is renamed automatically when a certain number of blocks are placed. So if a user waaaaay out in the wild is building a lot, then the region is named. 

happened.

Please test: https://ci.appveyor.com/api/buildjobs/s9ohpmlsa833teh9/artifacts/target%2FPopulationDensity.jar
