### ISSUE TITLE
teleporting animals without a lead

### ISSUE THREAD

**Issue by ghost** [MLG-Fortress/PopulationDensity#8]
Passive mobs teleport with you when using the /visit command. 

From testing it seems like any animal in a 5-6 block radius is teleported with you.

Tested on  1.11.2 spigot.

I updated population density a few days ago, and prior to that people needed to have the animals on a lead for them to be teleported with the player.

Even animals near players with the populationdensity.teleportanywhere permission are teleported. This is a real problem since people can now easily take animals from farms and pens.

**Comment by RoboMWM** [comment]
> From testing it seems like any animal in a 5-6 block radius is teleported with you.

That's exactly how it's intended to work.

If you want to make a request, either edit this ticket (and I'll reopen) or make a new one.

**Comment by ghost** [comment]
they are supposed to teleport even when they arent on a lead?

**Comment by RoboMWM** [comment]
Yes, that's how Big_Scary designed it.

**Comment by ghost** [comment]
I updated population density a few days ago, and prior to that people needed to have the animals on a lead for them to be teleported with the player.

Even animals near players with the populationdensity.teleportanywhere permission are teleported. This is a real problem since people can now easily take animals from farms and pens.

**Comment by RoboMWM** [comment]
What version did you update from?

Also
> If you want to make a request, either edit this ticket (and I'll reopen) or make a new one.
