### ISSUE TITLE
Absurd numbers of animals populate the newestregion.

### ISSUE THREAD

**Issue by zedwick** [MLG-Fortress/PopulationDensity#83]
PopulationDensity populates the newestregion with an absurd number of animals.

I disabled this feature on my own server long ago as a quick fix for this issue, but just noticed whilst testing another issue that this still occurs.

![2020-01-17_22 43 48](https://user-images.githubusercontent.com/991130/72651463-4cc59800-397b-11ea-8039-3c3346fa7b0b.png)

In the above screenshot I am floating above the region post. This server has been up for around 3-6 hours.

Tested using PopulationDensity 5.12 running Spigot.

**Comment by RoboMWM** [comment]
I personally haven't seen this on my server despite all the times I've used PopulationDensity so unsure how to determine what's going on here other than attempting to reproduce with debugging, or going through the code to see just what it does for spawning.

**Comment by DerekWearmouth** [comment]
I am having a similar issue with my old spawn region. A little context while testing my server, I afk;ed in this region over night and I do not believe it was just the newest region, as you can see from the /killall. I also did a /kill all animals before i Started AFK'ing.  There is no relevant errors in the logs other than SAML freezing mobs once they reach a cap of 1500.

My /killall animals from the region i AFK'ed in. 
![image](https://user-images.githubusercontent.com/11272589/73546521-ff2d3e80-4402-11ea-82a1-4419cc5940bf.png)
Region I AFK'ed in (more out of render distance but they all seem to be 50 blocks in radius or so around the region post)
![image](https://user-images.githubusercontent.com/11272589/73546371-bc6b6680-4402-11ea-8b5e-5e902c44ebc1.png)

I also noticed that the "grass regrows" has taken into effect at the same radius as the respawn animals. 
![image](https://user-images.githubusercontent.com/11272589/73548528-8fb94e00-4406-11ea-8c0b-9d8498bc3dbc.png)


Current Config (Removed irrelevant items from the config for this post)
PopulationDensity:
  NewPlayersSpawnInHomeRegion: false
  RespawnInHomeRegion: true
  CityWorldName: Spawn
  AllowTeleportation: true
  TeleportFromAnywhere: false
  MaxDistanceFromSpawnToUseHomeRegion: 25
  ManagedWorldName: the_isle
  DensityRatio: 1.0
  MaxIdleMinutes: 30
  LoginQueueEnabled: true
  ReservedSlotsForAdministrators: 2
  LoginQueueMessage: '%queuePosition% of %queueLength% in queue.  Reconnect within
    3 minutes to keep your place.  :)'
  HoursBetweenScans: 6
  BuildRegionPosts: true
  NewestRegionRequiresPermission: false
  GrassRegrows: true
  AnimalsRespawn: true
  TreesRegrow: true
  Max Monsters Nearby For More To Spawn: 2
  ThinOvercrowdedAnimalsAndMonsters: false
  ThinOvercrowdedIronGolems: false
  Abandoned Farm Animals Die: false
  Unused Minecarts Vanish: false
  MarkRemovedAnimalLocationsWithShrubs: true
  Remove Wild Skeletal Horses: true
  Disable Monster Grinders When Lagging: false
  Maximum Hoppers Per Chunk: 200
  Boot Idle Players When Lagging: false
  Capture Spigot Timings When Lagging: false
  KeepSpawnRegionPostLoaded: false
  KeepAllRegionPostsLoaded: false
  LaunchAndDropPlayers: false
  LaunchAndDropNewPlayers: false
  TeleportAnimals: true
  MinimumRegionPostY: 62
  PreciseWorldSpawn: true
  MinimumWoodAvailableToPlaceNewPlayers: 200
  MinimumResourceScoreToPlaceNewPlayers: 200
  PostProtectionDistance: 2
  Maximum Region Name Length: 10

**Comment by DerekWearmouth** [comment]
I set the first configs below, reloaded the server and the massive amounts of animal spawning stopped at the loaded region post. 

AnimalsRespawn: false
ThinOvercrowdedAnimalsAndMonsters: false
Abandoned Farm Animals Die: false

I then changed to the below settings and sat at a region post for 30 minute and once AnimalsRespawn was set to true, the massive amounts of animal spawning started up again. All animals spawned within 100 blocks of the center of the post. 

AnimalsRespawn: true
ThinOvercrowdedAnimalsAndMonsters: true
Abandoned Farm Animals Die: true

**Comment by zedwick** [comment]
The relevant code:

https://github.com/MLG-Fortress/PopulationDensity/blob/aa45f13956af69a7553dc888036af64714eb0f93/src/me/ryanhamshire/PopulationDensity/EntityEventHandler.java#L256-L305

The above runs when a mob spawns in the world.

For an animal to be respawned with a mob, the following must be true:

- Must be a monster being spawned
- respawnAnimals must be set to true in the config
- The block below must be a Grass block
- ? 5 respawn attempts must have been made between the last successful respawn attempt ?
- There must not be another Animal within 30 blocks of this location.
- monster must be a creeper, zombie, spider, skeleton or enderman

If all of the above are true, then an animal will be spawned and a patch of grass grown.

Given the above, especially the check for any nearby animals, there must be something else going on.

I have observed the animals spawning mostly in an apparent line or walls of a box, as seen in my picture above. So my theory is that the animals are spawning near the edges of the render distance, and the unloaded or semi-loaded entities along the edge are not being picked up as nearby entities. I'm not too familiar with lazy chunks and how entities are loaded/unloaded, so am not sure how to verify nor solve this if true.

**Comment by DerekWearmouth** [comment]
@zedwick I have observed the individual spawning and the pack spawning @mob locations within the same chunk as myself as well as in the 100 block-ish radius. I have my current view distance set to 14 when I was AFKing in the region. Honestly I did not notice this issue until i accidentally AFK'ed in a region for several hours on end.

What I am observing however is what appears to be the check for other animals not happening before packs/single animals are being spawned when zombies, skeletons, etc are around, especially those who do not start to burn right away during the daylight and/or are under a tree. However, the current version of population density was last updated jun of last year and I am currently running 1.15.2, it is possible that the variable within the check has maybe changed on the game end?

**Comment by zedwick** [comment]
After an embarrassing amount of time debugging this it turns out rather than checking each nearby entity to see if it is an animal, it would instead just repeatedly (up to the number of entities found in the area) check if the spawning monster is an animal.
