### ISSUE TITLE
ThinOvercrowdedIronGolems config option reverts to default

### ISSUE THREAD

**Issue by ghost** [MLG-Fortress/PopulationDensity#88]
```
PopulationDensity:
  ThinOvercrowdedIronGolems: false
```
This setting changes from `true` to `false`, even if I edit the file when the server is shut down, and then start it. Other settings changed do not revert their changes. I have never been able to make this setting `true`.

**Comment by RoboMWM** [comment]
what's `/version populationdensity` ?

**Comment by RoboMWM** [comment]
Ah, typo, capitalization is wrong when it attempts to read the config option. Thanks.

**Comment by RoboMWM** [comment]
`PopulationDensity.ThinOverCrowdedIronGolems` vs. `PopulationDensity.ThinOvercrowdedIronGolems`
