### ISSUE TITLE
Message not displayed for /invite'd player

### ISSUE THREAD

**Issue by mb243** [MLG-Fortress/PopulationDensity#9]
There is an option in my messages.yml, InviteNotification, that supports a message being sent to the player who receives a /invite. I haven't been able to find anything by searching BigScary's repo for this code, and it doesn't currently work. 

I would love to see this implemented for showing a message to the recipient of an /invite. 

Here's the code I have:

```
  InviteNotification:
    Text: '{0} has invited you to visit!'
    Notes: '0: inviter''s name'
```

**Comment by RoboMWM** [comment]
It works for me... what version are you using?

**Comment by mb243** [comment]
I think 5.8.4 of your plugin, I'll reinstall the latest just to be sure.
```
This server is running CraftBukkit version git-Spigot-7d78b81-775f1e1 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
```
Let me know if there are any permissions that might be influencing this and I'll check them :)

**Comment by RoboMWM** [comment]
Permission to /invite should be given by default. Try with no other plugins installed? I haven't touched anything regarding messaging players...

**Comment by mb243** [comment]
Yea, the players have permission to /invite, and can use it and see that they have invited another player, but the invited player doesn't receive any notification that they have been invited.

**Comment by RoboMWM** [comment]
Ah, Big_Scary removed this in 5.6. Probably because players were using it to spam other players. https://github.com/TechFortress/PopulationDensity/commit/d00b0c96655f57bc908b4d7cc555aee43f8f6d10#diff-9949b9a0b134153077ffcce4ac640ff4

**Comment by RoboMWM** [comment]
Easiest way to deal with this is to only send one invite message per session. Probably easiest to add metadata to the player. Would appreciate a PR though since I don't use this feature at all and as such won't be able to test nearly as easily (since it does require another player to test).
