### ISSUE TITLE
Players being moved into unloaded chunks, and falling into the void

### ISSUE THREAD

**Issue by Cobbet** [MLG-Fortress/PopulationDensity#92]
I believe this is actually due to a change in Paper build 200 (still a problem in 203), but I thought I should mention it. Reverted server to 199 and waiting to see what happens.

**Comment by RoboMWM** [comment]
yea, should be impossible for players to be teleported to chunks that aren't loaded. The only time this can possibly happen is on the first-ever join - and the plugin already waits 10 ticks (or 2 ticks, can't recall which) before performing any teleportation on a player.

**Comment by Apecengo** [comment]
Paper [just reverted the patch](https://github.com/PaperMC/Paper/commit/079a793b518b447e574bf6e4a54c2b4be4979a15) that could be causing this. Since updating to build 204 players haven't reported the issue again.

**Comment by RoboMWM** [comment]
cool thanks for the info.
