### ISSUE TITLE
Priority in queue does not work

### ISSUE THREAD

**Issue by JavierPM87** [MLG-Fortress/PopulationDensity#97]
Hello, I am testing the queue mode and it does not work for me, players get the message that the server is full, and not that it has a position in the queue.
I'm using the **populationdensity.prioritylogin** and **populationdensity.elitelogin** permissions to see what each one does, but I'm not getting results.
Instead the **populationdensity.adminlogin** works correctly.
I have this option activated **LoginQueueEnabled: true**.
I have also used the **/LoginPriority** command but it doesn't seem to change anything
Greetings

**Comment by RoboMWM** [comment]
provide config. iirc you need to ensure your limit set in popdensity's config is lower than the one in server.properties.

Also /version and /version PopulationDensity may help

**Comment by JavierPM87** [comment]
Paper version git-Paper-551 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[PopulationDensity] Loading PopulationDensity v5.13-209633c
max-players=24   -- server.properties



attached config and server log files

[latest.log](https://github.com/MLG-Fortress/PopulationDensity/files/6432705/latest.log)
[config poputation.txt](https://github.com/MLG-Fortress/PopulationDensity/files/6432712/config.poputation.txt)

**Comment by JavierPM87** [comment]
Sorry for the inconvenience, I found the conflict in the end, it's an EssentialsX option:

config.yml
Should Essentials override the vanilla "Server Full" message with its own from the language file?
Set to false to keep the vanilla message.
-use-custom-server-full-message: false

I had it in true, when I saw it, I knew it was the conflict, I set it to false and the queue works!

Greetings

**Comment by RoboMWM** [comment]
Thanks for reporting back on the cause!
